package bz.tikitmasta.customer;

import android.content.*; import android.graphics.*; import android.graphics.drawable.GradientDrawable; import android.os.Bundle; import android.text.InputType; import android.view.*; import android.widget.*;
import androidx.appcompat.app.AppCompatActivity; import com.google.android.material.button.MaterialButton; import com.google.android.material.textfield.TextInputEditText;
import org.json.*; import java.text.SimpleDateFormat; import java.util.*;

public class MainActivity extends AppCompatActivity {
 static final int NAVY=Color.rgb(3,24,43), NAVY2=Color.rgb(8,43,72), YELLOW=Color.rgb(255,205,0), BLUE=Color.rgb(31,111,235), BG=Color.rgb(245,247,250), INK=Color.rgb(9,30,54), MUTED=Color.rgb(91,108,126), GREEN=Color.rgb(16,166,92), RED=Color.rgb(220,45,60);
 LinearLayout root; ApiClient api=new ApiClient(); SharedPreferences prefs; String access="",refresh=""; JSONObject me;
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(NAVY);getWindow().setNavigationBarColor(NAVY);prefs=getSharedPreferences("tikit_customer_v2",MODE_PRIVATE);access=prefs.getString("access","");refresh=prefs.getString("refresh","");api.setAccessToken(access);if(access.isEmpty())welcome();else verifySession();}
 int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);} GradientDrawable bg(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
 TextView text(String s,int size,int color,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);v.setLineSpacing(0,1.12f);if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}
 MaterialButton button(String label,int color,View.OnClickListener click){MaterialButton b=new MaterialButton(this);b.setText(label);b.setAllCaps(false);b.setTextSize(15);b.setTextColor(color==YELLOW?NAVY:Color.WHITE);b.setBackgroundTintList(android.content.res.ColorStateList.valueOf(color));b.setCornerRadius(dp(14));b.setMinHeight(dp(52));b.setOnClickListener(click);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(5),0,dp(5));b.setLayoutParams(p);return b;}
 LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(16),dp(16),dp(16));c.setBackground(bg(Color.WHITE,18));c.setElevation(dp(2));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(7),0,dp(7));c.setLayoutParams(p);return c;}
 Space gap(int n){Space s=new Space(this);s.setLayoutParams(new LinearLayout.LayoutParams(1,dp(n)));return s;} void add(View v){root.addView(v);} void addAt(View v,int i){root.addView(v,Math.min(i,root.getChildCount()));}
 void page(String title,String subtitle,boolean nav){ScrollView sc=new ScrollView(this);sc.setFillViewport(true);sc.setBackgroundColor(BG);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(22),dp(18),nav?dp(88):dp(30));sc.addView(root);LinearLayout brand=new LinearLayout(this);brand.setGravity(Gravity.CENTER_VERTICAL);TextView mark=text("T",26,NAVY,true);mark.setGravity(Gravity.CENTER);mark.setBackground(bg(YELLOW,15));brand.addView(mark,new LinearLayout.LayoutParams(dp(52),dp(52)));LinearLayout names=new LinearLayout(this);names.setOrientation(LinearLayout.VERTICAL);names.setPadding(dp(11),0,0,0);names.addView(text("Tikit Masta",23,NAVY,true));names.addView(text("EVENTS MADE EASY",10,MUTED,true));brand.addView(names);add(brand);add(gap(22));add(text(title,28,INK,true));add(text(subtitle,14,MUTED,false));add(gap(14));FrameLayout frame=new FrameLayout(this);frame.addView(sc);if(nav)frame.addView(navbar(),new FrameLayout.LayoutParams(-1,dp(68),Gravity.BOTTOM));setContentView(frame);}
 View navbar(){LinearLayout n=new LinearLayout(this);n.setGravity(Gravity.CENTER);n.setPadding(dp(8),dp(7),dp(8),dp(7));n.setBackgroundColor(NAVY);String[] labs={"Home","Events","Tickets","Wallet","Profile"};View.OnClickListener[] cs={v->home(),v->events(),v->tickets(),v->wallet(),v->profile()};for(int i=0;i<labs.length;i++){TextView t=text(labs[i],12,Color.WHITE,i==0);t.setGravity(Gravity.CENTER);t.setOnClickListener(cs[i]);n.addView(t,new LinearLayout.LayoutParams(0,-1,1));}return n;}
 TextInputEditText field(String label,boolean secret){add(text(label,13,MUTED,true));TextInputEditText f=new TextInputEditText(this);f.setSingleLine();f.setTextSize(16);f.setTextColor(INK);f.setHint("Enter "+label.toLowerCase(Locale.US));f.setPadding(dp(14),dp(12),dp(14),dp(12));f.setBackground(bg(Color.WHITE,12));if(secret)f.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(56));p.setMargins(0,dp(4),0,dp(10));f.setLayoutParams(p);add(f);return f;} String val(TextInputEditText f){return f.getText()==null?"":f.getText().toString().trim();}

 void welcome(){page("Good events. Brighter communities.","Discover, buy, manage and enjoy events across Belize.",false);LinearLayout hero=card();hero.setPadding(dp(20),dp(28),dp(20),dp(28));hero.setBackground(new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{NAVY,Color.rgb(75,21,120)}));hero.addView(text("Tikit",36,Color.WHITE,true));hero.addView(text("Masta",36,YELLOW,true));hero.addView(gap(14));hero.addView(text("Your tickets, wallet and Belize's best events in one secure app.",16,Color.WHITE,false));add(hero);add(gap(12));add(button("Sign In",YELLOW,v->login()));add(button("Create Account",NAVY2,v->signupStart()));add(button("Explore Events",BLUE,v->events()));add(text("Connected securely to tikitmasta.com",12,MUTED,false));}
 void login(){page("Welcome back","Sign in with your Tikit Masta email and password.",false);TextInputEditText email=field("Email",false),pass=field("Password",true);add(button("Sign In",YELLOW,v->{JSONObject b=new JSONObject();try{b.put("login",val(email)).put("password",val(pass)).put("device_id",android.provider.Settings.Secure.getString(getContentResolver(),android.provider.Settings.Secure.ANDROID_ID)).put("device_name",android.os.Build.MODEL);}catch(Exception ignored){}api.post("/bz_eventpass/api/v2/auth/login",b,(r,e,s)->runOnUiThread(()->{if(e!=null){toast(friendly(e));return;}access=r.optString("access_token");refresh=r.optString("refresh_token");prefs.edit().putString("access",access).putString("refresh",refresh).apply();api.setAccessToken(access);home();}));}));add(button("Create Account",NAVY2,v->signupStart()));add(button("Explore without signing in",BLUE,v->events()));}
 void signupStart(){page("Create account","SMS verification protects every Tikit Masta account.",false);TextInputEditText name=field("Full name",false),email=field("Email",false),phone=field("Mobile number",false);add(button("Send SMS Code",YELLOW,v->{JSONObject p=obj("account_type","customer","name",val(name),"email",val(email),"phone",val(phone));api.rpc("/bz_eventpass/api/v1/auth/signup/start",p,(r,e,s)->runOnUiThread(()->{if(e!=null||r==null||!r.optBoolean("ok")){toast(e!=null?e:friendly(r==null?"server_error":r.optString("error")));return;}signupVerify(r.optInt("challenge_id"));}));}));add(button("Back to Sign In",NAVY2,v->login()));}
 void signupVerify(int challenge){page("Verify mobile","Enter the six-digit SMS code sent to your phone.",false);TextInputEditText code=field("SMS code",false);add(button("Verify Code",YELLOW,v->api.rpc("/bz_eventpass/api/v1/auth/signup/verify",obj("challenge_id",challenge,"code",val(code)),(r,e,s)->runOnUiThread(()->{if(e!=null||r==null||!r.optBoolean("ok")){toast(e!=null?e:friendly(r==null?"server_error":r.optString("error")));return;}signupPassword(challenge,r.optString("completion_token"));}))));}
 void signupPassword(int challenge,String token){page("Finish signup","Create a secure password of at least eight characters.",false);TextInputEditText pass=field("Password",true);add(button("Create Account",YELLOW,v->api.rpc("/bz_eventpass/api/v1/auth/signup/complete",obj("challenge_id",challenge,"completion_token",token,"password",val(pass)),(r,e,s)->runOnUiThread(()->{if(e!=null||r==null||!r.optBoolean("ok")){toast(e!=null?e:friendly(r==null?"server_error":r.optString("error")));return;}toast("Account created. Sign in now.");login();}))));}
 void verifySession(){api.get("/bz_eventpass/api/v2/me",(r,e,s)->runOnUiThread(()->{if(e==null){me=r;home();}else refreshSession();}));}
 void refreshSession(){api.setAccessToken("");api.post("/bz_eventpass/api/v2/auth/refresh",obj("refresh_token",refresh),(r,e,s)->runOnUiThread(()->{if(e!=null){clearSession();welcome();return;}access=r.optString("access_token");refresh=r.optString("refresh_token");prefs.edit().putString("access",access).putString("refresh",refresh).apply();api.setAccessToken(access);home();}));}
 void home(){page("Discover Belize","Live events, secure checkout and your tickets in one place.",true);LinearLayout hero=card();hero.setBackground(new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{NAVY2,Color.rgb(98,26,170)}));hero.addView(text("Summer Music Fest",22,Color.WHITE,true));hero.addView(text("Concerts • Festivals • Nightlife • Theatre • Sports",14,Color.WHITE,false));hero.addView(gap(12));hero.addView(button("Explore Events",YELLOW,v->events()));add(hero);add(text("QUICK ACCESS",12,MUTED,true));LinearLayout row=new LinearLayout(this);row.addView(tile("My Tickets","View QR passes",v->tickets()),new LinearLayout.LayoutParams(0,dp(130),1));Space sp=gap(1);sp.setLayoutParams(new LinearLayout.LayoutParams(dp(10),1));row.addView(sp);row.addView(tile("Wallet","Balance & activity",v->wallet()),new LinearLayout.LayoutParams(0,dp(130),1));add(row);}
 LinearLayout tile(String title,String sub,View.OnClickListener l){LinearLayout c=card();c.setGravity(Gravity.CENTER);TextView a=text(title,18,INK,true);a.setGravity(Gravity.CENTER);c.addView(a);TextView b=text(sub,13,MUTED,false);b.setGravity(Gravity.CENTER);c.addView(b);c.setOnClickListener(l);return c;}
 void events(){page("Events","Discover concerts, festivals, nightlife, theatre and more.",!access.isEmpty());TextView loading=text("Loading live events…",15,MUTED,false);add(loading);api.rpc("/bz_eventpass/api/v1/events",new JSONObject(),(r,e,s)->runOnUiThread(()->{root.removeView(loading);if(e!=null||r==null||!r.optBoolean("ok")){notice("Events unavailable",e!=null?e:r==null?"No server response":r.optString("error"),RED);return;}JSONArray a=r.optJSONArray("events");if(a==null||a.length()==0){notice("No published events","Check again soon for new experiences.",BLUE);return;}for(int i=0;i<a.length();i++)eventCard(a.optJSONObject(i));}));if(access.isEmpty())add(button("Sign In",NAVY,v->login()));}
 void eventCard(JSONObject e){LinearLayout c=card();c.addView(text(e.optString("name","Event"),20,INK,true));c.addView(text(pretty(e.optString("start_datetime"))+"\n"+e.optString("venue_name")+" • "+e.optString("city"),14,MUTED,false));c.addView(gap(8));String av=e.optString("availability","available");c.addView(text(av.replace('_',' ').toUpperCase(Locale.US),11,"sold_out".equals(av)?RED:GREEN,true));c.addView(button(access.isEmpty()?"Sign in to buy":"View Tickets",YELLOW,v->{if(access.isEmpty())login();else eventDetail(e.optInt("id"),e);}));add(c);}
 void eventDetail(int id,JSONObject summary){page(summary.optString("name"),pretty(summary.optString("start_datetime"))+" • "+summary.optString("venue_name"),true);TextView l=text("Loading ticket types…",15,MUTED,false);add(l);api.rpc("/bz_eventpass/api/v1/event/"+id,new JSONObject(),(r,e,s)->runOnUiThread(()->{root.removeView(l);if(e!=null||r==null||!r.optBoolean("ok")){notice("Unable to load tickets",e,RED);return;}JSONArray types=r.optJSONObject("event").optJSONArray("ticket_types");for(int i=0;types!=null&&i<types.length();i++){JSONObject t=types.optJSONObject(i);LinearLayout c=card();c.addView(text(t.optString("name"),19,INK,true));c.addView(text("BZD $"+String.format(Locale.US,"%.2f",t.optDouble("price")),20,NAVY2,true));c.addView(text(t.optString("availability").toUpperCase(Locale.US),11,GREEN,true));c.addView(button("Reserve Ticket",YELLOW,v->reserve(id,t.optInt("id"))));add(c);}}));}
 void reserve(int event,int type){api.post("/bz_eventpass/api/v2/orders/reserve",obj("event_id",event,"ticket_type_id",type,"quantity",1),(r,e,s)->runOnUiThread(()->{if(e!=null){toast(friendly(e));return;}notice("Reservation created",r.optString("order_number")+" • BZD $"+String.format(Locale.US,"%.2f",r.optDouble("total"))+"\nComplete payment using an available server-verified method.",GREEN);}));}
 void tickets(){if(!requireLogin())return;page("My Tickets","Upcoming and past tickets linked to your account.",true);loadList("/bz_eventpass/api/v2/customer/tickets","tickets",x->{LinearLayout c=card();c.addView(text(x.optString("event"),19,INK,true));c.addView(text(x.optString("ticket_type")+"\n"+x.optString("number"),14,MUTED,false));c.addView(text(x.optString("state").toUpperCase(Locale.US),11,GREEN,true));c.addView(gap(8));TextView qr=text("▣\n"+x.optString("access_code"),18,NAVY,true);qr.setGravity(Gravity.CENTER);qr.setPadding(0,dp(12),0,dp(12));c.addView(qr);add(c);});}
 void wallet(){if(!requireLogin())return;page("Wallet","Your Tikit Masta spending account and transactions.",true);api.get("/bz_eventpass/api/v2/customer/wallet",(r,e,s)->runOnUiThread(()->{if(e!=null){notice("Wallet unavailable",friendly(e),RED);return;}LinearLayout balance=card();balance.setBackground(new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{Color.rgb(91,33,182),Color.rgb(124,40,220)}));balance.addView(text("BALANCE",12,Color.WHITE,true));balance.addView(text("BZD $"+String.format(Locale.US,"%.2f",r.optDouble("balance")),30,Color.WHITE,true));addAt(balance,3);JSONArray a=r.optJSONArray("transactions");for(int i=0;a!=null&&i<a.length();i++){JSONObject x=a.optJSONObject(i);LinearLayout c=card();c.addView(text(x.optString("type").replace('_',' ').toUpperCase(Locale.US),14,INK,true));c.addView(text((x.optDouble("amount")>=0?"+":"")+"BZD $"+String.format(Locale.US,"%.2f",x.optDouble("amount")),17,x.optDouble("amount")>=0?GREEN:RED,true));c.addView(text(x.optString("reference"),12,MUTED,false));add(c);}}));}
 void profile(){if(!requireLogin())return;page("My Account","Manage your Tikit Masta profile and session.",true);api.get("/bz_eventpass/api/v2/me",(r,e,s)->runOnUiThread(()->{if(e!=null){notice("Profile unavailable",friendly(e),RED);return;}JSONObject u=r.optJSONObject("user");LinearLayout c=card();c.addView(text(u.optString("name"),22,INK,true));c.addView(text(u.optString("email"),14,MUTED,false));c.addView(gap(10));c.addView(text("My Tickets\nMy Orders\nWallet\nNotifications\nSupport",16,INK,false));addAt(c,3);}));add(button("Log Out",RED,v->logout()));}
 interface ItemRenderer{void show(JSONObject item);} void loadList(String path,String key,ItemRenderer renderer){TextView l=text("Loading…",15,MUTED,false);add(l);api.get(path,(r,e,s)->runOnUiThread(()->{root.removeView(l);if(e!=null){notice("Unable to load",friendly(e),RED);return;}JSONArray a=r.optJSONArray(key);if(a==null||a.length()==0){notice("Nothing here yet","New activity will appear here.",BLUE);return;}for(int i=0;i<a.length();i++)renderer.show(a.optJSONObject(i));}));}
 boolean requireLogin(){if(access.isEmpty()){login();return false;}return true;} void logout(){api.post("/bz_eventpass/api/v2/auth/logout",new JSONObject(),(r,e,s)->runOnUiThread(()->{clearSession();welcome();}));} void clearSession(){access="";refresh="";me=null;api.setAccessToken("");prefs.edit().clear().apply();}
 void notice(String title,String body,int color){LinearLayout c=card();c.setBackground(bg(Color.WHITE,18));c.addView(text(title,19,color,true));c.addView(text(body==null?"":friendly(body),14,MUTED,false));add(c);} void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();} String friendly(String s){return(s==null?"Unexpected error":s).replace('_',' ');} String pretty(String raw){try{Date d=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss",Locale.US).parse(raw);return new SimpleDateFormat("EEE, d MMM yyyy • h:mm a",Locale.US).format(d);}catch(Exception e){return raw;}}
 JSONObject obj(Object... values){JSONObject o=new JSONObject();try{for(int i=0;i+1<values.length;i+=2)o.put(String.valueOf(values[i]),values[i+1]);}catch(Exception ignored){}return o;}
}
