package bz.tikitmasta.mobile;

import android.content.*; import android.graphics.*; import android.graphics.drawable.GradientDrawable; import android.net.Uri; import android.os.Bundle; import android.text.InputType; import android.view.*; import android.widget.*;
import androidx.appcompat.app.AppCompatActivity;
import com.google.android.material.button.MaterialButton; import com.google.android.material.textfield.TextInputEditText;
import com.journeyapps.barcodescanner.ScanContract; import com.journeyapps.barcodescanner.ScanOptions;
import org.json.*; import java.io.InputStream; import java.net.URL; import java.text.SimpleDateFormat; import java.util.*;

public class MainActivity extends AppCompatActivity {
 static final int PURPLE=Color.rgb(91,33,182), DARK=Color.rgb(31,22,48), GOLD=Color.rgb(245,158,11), BG=Color.rgb(248,247,252), MUTED=Color.rgb(105,96,120);
 LinearLayout content; SharedPreferences prefs; ApiClient api; TextView connectionDot;
 final androidx.activity.result.ActivityResultLauncher<ScanOptions> scanner=registerForActivityResult(new ScanContract(),r->{if(r.getContents()!=null)submitScan(r.getContents());});
 @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("tikit",MODE_PRIVATE);getWindow().setStatusBarColor(DARK);getWindow().setNavigationBarColor(DARK);showHome();}
 int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);} GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
 TextView text(String s,int z,int c,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setLineSpacing(0,1.12f);if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}
 Space gap(int h){Space s=new Space(this);s.setLayoutParams(new LinearLayout.LayoutParams(1,dp(h)));return s;} void add(View v){content.addView(v);}
 MaterialButton button(String label,int color,View.OnClickListener l){MaterialButton b=new MaterialButton(this);b.setText(label);b.setTextSize(15);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setBackgroundTintList(android.content.res.ColorStateList.valueOf(color));b.setCornerRadius(dp(14));b.setMinHeight(dp(52));b.setOnClickListener(l);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(5),0,dp(5));b.setLayoutParams(p);return b;}
 LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(18),dp(18),dp(18),dp(18));c.setBackground(bg(Color.WHITE,18));c.setElevation(dp(2));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(7),0,dp(7));c.setLayoutParams(p);return c;}
 void page(String kicker,String heading,String sub){ScrollView sc=new ScrollView(this);sc.setFillViewport(true);sc.setBackgroundColor(BG);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(20),dp(24),dp(20),dp(34));sc.addView(content);LinearLayout brand=new LinearLayout(this);brand.setGravity(Gravity.CENTER_VERTICAL);TextView logo=text("TM",18,Color.WHITE,true);logo.setGravity(Gravity.CENTER);logo.setBackground(bg(PURPLE,15));brand.addView(logo,new LinearLayout.LayoutParams(dp(48),dp(48)));LinearLayout names=new LinearLayout(this);names.setOrientation(LinearLayout.VERTICAL);names.setPadding(dp(12),0,0,0);names.addView(text("TIKIT MASTA",21,DARK,true));connectionDot=text("●  "+(configured()?"Connected account":"Setup required"),12,configured()?Color.rgb(16,145,82):GOLD,true);names.addView(connectionDot);brand.addView(names);add(brand);add(gap(24));add(text(kicker.toUpperCase(Locale.US),12,PURPLE,true));add(text(heading,28,DARK,true));add(gap(5));add(text(sub,15,MUTED,false));add(gap(18));setContentView(sc);}
 boolean configured(){return!token().isEmpty()&&!server().contains("your-odoo");} String server(){return prefs.getString("server","https://your-odoo-domain.com").replaceAll("/+$","");} String token(){return prefs.getString("device_token","");} void initApi(){api=new ApiClient(server());} void back(){add(gap(12));add(button("← Back to dashboard",DARK,v->showHome()));add(gap(64));}

 void showHome(){page("Belize events, one app","Discover. Sell. Scan.","Live event discovery for customers and fast venue operations for your team.");LinearLayout hero=card();hero.setBackground(new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{PURPLE,Color.rgb(126,53,205)}));hero.addView(text("What’s happening?",24,Color.WHITE,true));TextView hs=text("Browse upcoming experiences and buy securely from Tikit Masta.",15,Color.rgb(239,232,255),false);hs.setPadding(0,dp(7),0,dp(12));hero.addView(hs);hero.addView(button("Explore events",GOLD,v->events()));add(hero);add(gap(13));add(text("VENUE OPERATIONS",12,MUTED,true));LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.addView(actionCard("▣","Scan tickets","Fast QR check-in",v->scan()),new LinearLayout.LayoutParams(0,dp(160),1));Space x=gap(1);x.setLayoutParams(new LinearLayout.LayoutParams(dp(10),1));row.addView(x);row.addView(actionCard("$","Gate sales","Sell & admit",v->gateSale()),new LinearLayout.LayoutParams(0,dp(160),1));add(row);add(gap(8));add(button("Promoter dashboard",PURPLE,v->dashboard()));add(button("Connection settings",DARK,v->settings()));add(gap(16));add(text("Tikit Masta Android  •  API v1.7  •  App v1.1",12,MUTED,false));}
 LinearLayout actionCard(String icon,String title,String sub,View.OnClickListener l){LinearLayout c=card();c.setGravity(Gravity.CENTER_VERTICAL);TextView i=text(icon,28,PURPLE,true);i.setGravity(Gravity.CENTER);c.addView(i,new LinearLayout.LayoutParams(-1,dp(52)));TextView t=text(title,17,DARK,true);t.setGravity(Gravity.CENTER);c.addView(t);TextView s=text(sub,13,MUTED,false);s.setGravity(Gravity.CENTER);c.addView(s);c.setOnClickListener(l);return c;}

 void settings(){page("App setup","Connect to Odoo","Use your Odoo 18 HTTPS address. Staff tools also require an active scanner device token.");TextInputEditText s=field("Odoo server URL",server(),false),t=field("Scanner device token",token(),true);add(button("Save and test connection",PURPLE,v->{prefs.edit().putString("server",value(s)).putString("device_token",value(t)).apply();testConnection();}));back();}
 void testConnection(){initApi();toast("Testing connection…");api.post("/bz_eventpass/api/v1/scanner/status",new J().put("device_token",token()).get(),(r,e)->runOnUiThread(()->{if(e==null&&r!=null&&r.optBoolean("ok")){connectionDot.setText("●  Connected");connectionDot.setTextColor(Color.rgb(16,145,82));toast("Connected successfully");}else toast("Saved. "+(e!=null?e:r==null?"No response":friendly(r.optString("error"))));}));}

 void events(){page("Discover","Upcoming events","Live availability from Tikit Masta.");TextView loading=text("Loading events…",15,MUTED,false);add(loading);add(button("Refresh events",DARK,v->events()));back();initApi();api.post("/bz_eventpass/api/v1/events",new JSONObject(),(r,e)->runOnUiThread(()->{content.removeView(loading);if(e!=null||r==null||!r.optBoolean("ok")){showError(e!=null?e:r==null?"No response":r.optString("error"));return;}JSONArray a=r.optJSONArray("events");if(a==null||a.length()==0){addAt(text("No published events yet.",16,MUTED,false),3);return;}for(int i=a.length()-1;i>=0;i--)eventCard(a.optJSONObject(i));}));}
 void eventCard(JSONObject x){LinearLayout c=card();String poster=x.optString("poster_url");if(!poster.isEmpty()&&!"false".equals(poster)){ImageView image=new ImageView(this);image.setScaleType(ImageView.ScaleType.CENTER_CROP);image.setBackground(bg(Color.rgb(233,228,244),14));c.addView(image,new LinearLayout.LayoutParams(-1,dp(170)));loadImage(image,new ApiClient(server()).absolute(poster));c.addView(gap(14));}String av=x.optString("availability","available");c.addView(text(av.replace('_',' ').toUpperCase(Locale.US),11,"sold_out".equals(av)?Color.rgb(190,30,45):Color.rgb(16,145,82),true));c.addView(text(x.optString("name","Event"),21,DARK,true));c.addView(gap(5));c.addView(text(prettyDate(x.optString("start_datetime"))+"\n"+place(x),14,MUTED,false));c.addView(gap(10));c.addView(button("View event and tickets",PURPLE,v->eventDetail(x.optInt("id"),x)));addAt(c,3);}
 void eventDetail(int id,JSONObject summary){page("Event details",summary.optString("name"),prettyDate(summary.optString("start_datetime"))+"  •  "+place(summary));TextView loading=text("Loading ticket availability…",15,MUTED,false);add(loading);back();initApi();api.post("/bz_eventpass/api/v1/event/"+id,new JSONObject(),(r,e)->runOnUiThread(()->{content.removeView(loading);if(e!=null||r==null||!r.optBoolean("ok")){showError(e!=null?e:r.optString("error"));return;}JSONObject ev=r.optJSONObject("event");JSONArray types=ev.optJSONArray("ticket_types");addAt(text("TICKETS",12,PURPLE,true),5);if(types==null||types.length()==0)addAt(text("Tickets are not on sale yet.",15,MUTED,false),6);else for(int i=types.length()-1;i>=0;i--){JSONObject t=types.optJSONObject(i);LinearLayout c=card();c.addView(text(t.optString("name"),18,DARK,true));c.addView(text(t.optString("description"),14,MUTED,false));c.addView(gap(6));c.addView(text(t.optString("currency")+" "+String.format(Locale.US,"%.2f",t.optDouble("price")),20,PURPLE,true));c.addView(text(t.optString("availability").toUpperCase(Locale.US),11,"sold_out".equals(t.optString("availability"))?Color.RED:Color.rgb(16,145,82),true));addAt(c,6);}addAt(button("Buy tickets securely",GOLD,v->startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(new ApiClient(server()).absolute(summary.optString("public_url")))))),content.getChildCount()-1);}));}

 void scan(){if(!configured()){toast("Connect the Odoo server and device token first");settings();return;}ScanOptions o=new ScanOptions();o.setPrompt("Align the Tikit Masta QR code inside the frame");o.setBeepEnabled(true);o.setOrientationLocked(true);scanner.launch(o);}
 void submitScan(String value){page("Gate check-in","Validating ticket","Checking this ticket live against Odoo.");ProgressBar p=new ProgressBar(this);add(p);initApi();api.post("/bz_eventpass/api/v1/ticket/scan",new J().put("device_token",token()).put("scan_value",value).get(),(r,e)->runOnUiThread(()->{content.removeView(p);boolean ok=e==null&&r!=null&&r.optBoolean("ok");LinearLayout result=card();result.setBackground(bg(ok?Color.rgb(225,250,237):Color.rgb(255,232,235),18));result.addView(text(ok?"✓  ACCEPTED":"✕  NOT ACCEPTED",25,ok?Color.rgb(0,120,69):Color.rgb(190,30,45),true));result.addView(gap(8));result.addView(text(ok?ticketSummary(r.optJSONObject("ticket")):(e!=null?e:r==null?"No server response":friendly(r.optString("error"))),16,DARK,false));add(result);add(button("Scan next ticket",PURPLE,v->scan()));back();}));}
 String ticketSummary(JSONObject t){return t==null?"Ticket checked in successfully":safe(t,"customer_name","Guest")+"\n"+safe(t,"event_name","")+"\n"+safe(t,"ticket_type_name","");}

 void gateSale(){if(!configured()){toast("Connect a scanner device first");settings();return;}page("Venue sales","New gate sale","Issue tickets directly at the entrance.");TextInputEditText event=field("Event ID","",false),type=field("Ticket type ID","",false),qty=field("Quantity","1",false),name=field("Customer name","",false),email=field("Customer email","",false),phone=field("Customer phone","",false);Spinner pay=new Spinner(this);pay.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"cash","card","wallet"}));add(text("Payment method",13,MUTED,true));add(pay);CheckBox admit=new CheckBox(this);admit.setText("Admit tickets immediately");add(admit);add(button("Complete gate sale",GOLD,v->{if(value(event).isEmpty()||value(type).isEmpty()){toast("Event ID and ticket type are required");return;}initApi();JSONObject p=new J().put("device_token",token()).put("event_id",value(event)).put("ticket_type_id",value(type)).put("quantity",value(qty)).put("customer_name",value(name)).put("customer_email",value(email)).put("customer_phone",value(phone)).put("payment_method",pay.getSelectedItem()).putRaw("admit",admit.isChecked()).get();api.post("/bz_eventpass/api/v1/gate/sale",p,(r,e)->runOnUiThread(()->{if(e!=null||r==null||!r.optBoolean("ok")){toast(e!=null?e:r==null?"No response":friendly(r.optString("error")));return;}JSONObject sale=r.optJSONObject("gate_sale");toast("Sale complete • "+sale.optString("receipt_number")+" • "+sale.optString("currency")+" "+sale.optDouble("total_amount"));}));}));back();}

 void dashboard(){page("Business","Promoter dashboard","Live sales, commission and settlement information.");TextInputEditText account=field("Promoter account number","",false),key=field("API token","",true);add(button("Load dashboard",PURPLE,v->{initApi();api.post("/bz_eventpass/api/v1/promoter/dashboard",new J().put("account_number",value(account)).put("api_token",value(key)).get(),(r,e)->runOnUiThread(()->{if(e!=null||r==null||!r.optBoolean("ok")){toast(e!=null?e:r==null?"No response":friendly(r.optString("error")));return;}JSONObject p=r.optJSONObject("promoter");LinearLayout c=card();c.addView(text(p.optString("name"),23,DARK,true));c.addView(text(p.optString("business_plan").toUpperCase(Locale.US)+" PLAN  •  "+p.optString("agreement_status").toUpperCase(Locale.US),12,PURPLE,true));c.addView(gap(14));c.addView(metric("Tickets sold",String.valueOf(p.optInt("tickets_sold"))));c.addView(metric("Attributed revenue",money(p,p.optDouble("attributed_revenue"))));c.addView(metric("Commission due",money(p,p.optDouble("commission_due"))));JSONObject pa=p.optJSONObject("payment_accounts");c.addView(metric("Payment routing",pa==null?"":pa.optString("routing").replace('_',' ')));addAt(c,content.getChildCount()-1);}));}));back();}
 LinearLayout metric(String label,String value){LinearLayout r=new LinearLayout(this);r.setPadding(0,dp(7),0,dp(7));r.addView(text(label,14,MUTED,false),new LinearLayout.LayoutParams(0,-2,1));r.addView(text(value,16,DARK,true));return r;}

 TextInputEditText field(String hint,String initial,boolean secret){add(text(hint,13,MUTED,true));TextInputEditText f=new TextInputEditText(this);f.setHint("Enter "+hint.toLowerCase(Locale.US));f.setHintTextColor(Color.rgb(145,137,158));f.setTextColor(DARK);f.setText(initial);f.setTextSize(16);f.setSingleLine(true);f.setPadding(dp(14),dp(14),dp(14),dp(14));f.setBackground(bg(Color.WHITE,12));if(secret)f.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(58));p.setMargins(0,dp(4),0,dp(12));f.setLayoutParams(p);add(f);return f;}
 void addAt(View v,int index){content.addView(v,Math.min(Math.max(0,index),content.getChildCount()));} void showError(String msg){LinearLayout c=card();c.addView(text("Couldn’t load data",18,Color.rgb(190,30,45),true));c.addView(text(msg,14,MUTED,false));addAt(c,3);} String value(TextInputEditText f){return f.getText()==null?"":f.getText().toString().trim();}
 String place(JSONObject x){String v=x.optString("venue_name"),c=x.optString("city");return v+(v.isEmpty()||c.isEmpty()?"":" • ")+c;} String prettyDate(String raw){try{Date d=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss",Locale.US).parse(raw);return new SimpleDateFormat("EEE, MMM d • h:mm a",Locale.US).format(d);}catch(Exception e){return raw;}} String safe(JSONObject o,String k,String f){String s=o.optString(k);return s.isEmpty()||"false".equals(s)?f:s;} String friendly(String e){return e.replace('_',' ');} String money(JSONObject p,double n){return p.optString("currency")+" "+String.format(Locale.US,"%.2f",n);}
 void loadImage(ImageView image,String url){new Thread(()->{try(InputStream in=new URL(url).openStream()){Bitmap b=BitmapFactory.decodeStream(in);runOnUiThread(()->image.setImageBitmap(b));}catch(Exception ignored){}}).start();} void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
 static class J{JSONObject o=new JSONObject();J put(String k,Object v){try{o.put(k,String.valueOf(v));}catch(Exception ignored){}return this;}J putRaw(String k,Object v){try{o.put(k,v);}catch(Exception ignored){}return this;}JSONObject get(){return o;}}
}
